baseURL = ""
languageCode = "en-us"
title = "Carles Moreno Magrans"
theme = "resume"

[params]
firstName = "Carles"
lastName = "Moreno Magrans"
address = "North Bend, WA, US"
profileImage = "/img/profile.jpg"
email = "carlesm@outlook.com"
description = "Software Engineer making the web empower everyone to achieve more."

# what sections
showSkills = true
showProjects = true
showOpenSource = false
showPublications = false
showExperience = true
showEducation = true

showQr = false
contactNote = "Software Engineer"

[[params.handles]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/carles2m"

[[params.handles]]
name = "Bitbucket"
link = "https://bitbucket.org/mushn/"

[[params.handles]]
name = "GitHub"
link = "https://github.com/carles2m"

[params.google.analytics]
trackerID = "UA-122301273-1"

#only required for search
[outputs]
home = ["HTML", "JSON"]